import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import ClientAOSProvider from "./ClientAOSProvider";

export const metadata = {
  title: "Zakaria.dev",
  description: "Generated by create next app",
};

const ralwayFont = Raleway({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ralwayFont.className} antialiased `}>
        <ClientAOSProvider>
          <div className=" text-white w-screen overflow-x-hidden">
            <Navbar />
            {children}
            <Footer />
            <div className="spacing h-10 bg-black"></div>
          </div>
        </ClientAOSProvider>
      </body>
    </html>
  );
}
