import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ralwayFont = Raleway({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ralwayFont.className} antialiased `}>
        <div className="bgLayer w-screen h-screen overflow-auto bg-center bg-cover overflow-x-hidden">
          <div className="grad-overlay text-white">
            <Navbar />
            {children}
            <Footer/>
            <div className="spacing h-10 bg-black"></div>
          </div>
        </div>
      </body>
    </html>
  );
}
